#!/bin/bash
set -euo pipefail

MODE="${1:-unrestricted}"

ALLOWLIST_DIR="/opt/allowlist"
ALLOWLIST_FILE="$ALLOWLIST_DIR/allowlist.txt"
DNSMASQ_CONF="/etc/dnsmasq.d/allowlist.conf"

UPSTREAM_V4="1.1.1.1"
UPSTREAM_V6="2606:4700:4700::1111"

write_config() {
    local mode="$1"

    # Clean up stale configs from previous versions
    rm -f /etc/dnsmasq.d/00-initial.conf /etc/dnsmasq.d/99-allowlist.conf

    {
        echo "# Generated by generate-dnsmasq.sh — do not edit manually"
        echo "# Mode: $mode"
        echo "# $(date)"
        echo ""
        echo "no-resolv"
        echo "bind-interfaces"
        echo "listen-address=127.0.0.1"
        echo "port=53"
        echo "domain-needed"
        echo "bogus-priv"
        echo ""

        if [ "$mode" = "locked" ]; then
            if [ ! -f "$ALLOWLIST_FILE" ] || [ ! -s "$ALLOWLIST_FILE" ]; then
                echo "Error: $ALLOWLIST_FILE is missing or empty" >&2
                exit 1
            fi

            while IFS= read -r domain || [ -n "$domain" ]; do
                domain="$(echo "$domain" | xargs)"
                [ -z "$domain" ] && continue
                [[ "$domain" == \#* ]] && continue
                domain="${domain#\*.}"
                echo "server=/$domain/$UPSTREAM_V4"
                echo "server=/$domain/$UPSTREAM_V6"
            done < "$ALLOWLIST_FILE"
        else
            echo "# Forward all queries"
            echo "server=$UPSTREAM_V4"
            echo "server=$UPSTREAM_V6"
        fi
    } > "$DNSMASQ_CONF"

    chown root:root "$DNSMASQ_CONF"
    chmod 644 "$DNSMASQ_CONF"
}

write_config "$MODE"
systemctl restart dnsmasq
echo "dnsmasq: $MODE — deployed to $DNSMASQ_CONF and restarted"
