"""Blocklist subpackage -- facade re-exporting the blocklist public API.

sources.json is the source of truth for upstream blocklists.  All mutable
blocklist files (sources.json, blocklist-custom.txt, blocklist-exclude.txt,
blocklist-exceptions.txt) live in both the repo (ARK_REPO_ETC_PATH) and
live (ARK_DATA_PATH) copies; netmgr always edits the repo copy, then
_sync_to_live() pushes to the live dir.  User commits repo changes for
portability.
"""
from __future__ import annotations

from ._config import (
    ARK_REPO_ETC_PATH,
    BATCH_SIZE,
    CUSTOM_FILE,
    CUSTOM_HEADER,
    CUSTOM_REPO_FILE,
    DOMAIN_RE,
    DOMAINS_DIR,
    DOWNLOAD_TIMEOUT,
    EXCEPTIONS_FILE,
    EXCEPTIONS_HEADER,
    EXCEPTIONS_REPO_FILE,
    EXCLUDE_FILE,
    EXCLUDE_HEADER,
    EXCLUDE_REPO_FILE,
    MAX_DOMAIN_LEN,
    OUTPUT_FILE,
    OUTPUT_FORMAT,
    REPO_DOMAINS_DIR,
    SOURCES_FILE,
    SOURCES_REPO_FILE,
    UPSTREAM_DIR,
    USER_AGENT,
    BlocklistError,
    _read_domains,
    _read_exceptions,
    _read_exclude,
    _repo_file,
    _sync_to_live,
    _valid_domain,
    _write_exceptions,
    _write_exclude,
    _write_repo_file,
    ensure_domains_dir,
    ensure_upstream_dir,
)
from .download import download, extract_zip, normalize_url
from .generate import generate
from .manage import (
    add,
    block,
    blocklist_counts,
    exempt_add,
    exempt_list,
    exempt_remove,
    lookup,
    purge,
    remove,
    search,
    stats,
    unblock,
    verify,
)

__all__ = [
    "ARK_REPO_ETC_PATH",
    "BATCH_SIZE",
    "BlocklistError",
    "CUSTOM_FILE",
    "CUSTOM_HEADER",
    "CUSTOM_REPO_FILE",
    "DOMAIN_RE",
    "DOMAINS_DIR",
    "DOWNLOAD_TIMEOUT",
    "EXCEPTIONS_FILE",
    "EXCEPTIONS_HEADER",
    "EXCEPTIONS_REPO_FILE",
    "EXCLUDE_FILE",
    "EXCLUDE_HEADER",
    "EXCLUDE_REPO_FILE",
    "MAX_DOMAIN_LEN",
    "OUTPUT_FILE",
    "OUTPUT_FORMAT",
    "REPO_DOMAINS_DIR",
    "SOURCES_FILE",
    "SOURCES_REPO_FILE",
    "UPSTREAM_DIR",
    "USER_AGENT",
    "_read_domains",
    "_read_exceptions",
    "_read_exclude",
    "_repo_file",
    "_sync_to_live",
    "_valid_domain",
    "_write_exceptions",
    "_write_exclude",
    "_write_repo_file",
    "add",
    "block",
    "blocklist_counts",
    "download",
    "ensure_domains_dir",
    "ensure_upstream_dir",
    "exempt_add",
    "exempt_list",
    "exempt_remove",
    "extract_zip",
    "generate",
    "lookup",
    "normalize_url",
    "purge",
    "remove",
    "search",
    "stats",
    "unblock",
    "verify",
]
