#!/bin/bash

# Simple script to handle a DIY shutdown menu with rofi.
#
# Requirements:
# - rofi
# - systemd (can be replaced for other init systems if needed)
#
# Instructions:
# - Save this file as power.sh
# - Make it executable: chmod +x /path/to/power.sh
# - Run it

ROFI_THEME="$HOME/.config/sway/rofi/power.rasi"

chosen=$(printf '%s\n' "[Cancel]" "Logout" "Suspend" "Shutdown" "Reboot" | \
    rofi -dmenu -i -p "Power Menu" -theme "$ROFI_THEME")

case "$chosen" in
    "Logout") pkill sway ;;
    "Suspend") sudo systemctl suspend ;;
    "Shutdown") sudo systemctl poweroff ;;
    "Reboot") sudo systemctl reboot ;;
    *) exit 0 ;; # Exit on cancel or invalid input
esac

