# Borders & gaps
default_border pixel 2
default_floating_border pixel 4
titlebar_padding 15 4
gaps inner 12
gaps outer 14

# Float commonly-floating apps
for_window [app_id="mpv"] floating enable, move position center
for_window [app_id="galculator"] floating enable, move position center
for_window [app_id="transmission-gtk"] floating enable, move position center
for_window [app_id="pavucontrol"] floating enable, move position center
for_window [app_id="blueman-manager"] floating enable, move position center

# Kitty — no title bar on Wayland
for_window [app_id="kitty"] titlebar_padding 0, gaps inner 0

# Inhibit idle for fullscreen apps
for_window [app_id="firefox|brave|mpv|vlc|chromium"] inhibit_idle fullscreen
