[behavior]
autohide = true
hide-timeout = 400
hotspot-delay = 20
hotspot-layer = "overlay"

[layout]
position = "bottom"
alignment = "center"
mb = 10

[appearance]
icon-size = 48
opacity = 85
css-file = "style.css"
launch-animation = true

[launcher]
launcher-cmd = "rofi -show drun -config ~/.config/sway/rofi/config.rasi"
launcher-pos = "end"
