# --- linux_setup additions ---

alias docker="podman"
alias reboot='sudo systemctl reboot'
alias poweroff='sudo systemctl poweroff'
alias suspend='sudo systemctl suspend'
alias rm='rm -I'


if [ -z "${DISPLAY}" ] && [ -z "${WAYLAND_DISPLAY}" ] && [ "${XDG_VTNR}" -eq 1 ]; then
    exec sway
fi

# opencode
export PATH=/home/mike/.opencode/bin:$PATH
# zed
export PATH=$HOME/.local/bin:$PATH
# go
export PATH=$HOME/go/bin:$PATH


