#!/bin/bash
set -euo pipefail

MODE="${1:-unrestricted}"

ALLOWLIST_DIR="@ALLOWLIST_PATH@"
DNSMASQ_CONF="/etc/dnsmasq.d/allowlist.conf"

UPSTREAM_V4="@DNS_PRIMARY@"
UPSTREAM_V6="@DNS_SECONDARY@"

write_config() {
    local mode="$1"

    # Clean up stale configs from previous versions
    rm -f /etc/dnsmasq.d/00-initial.conf /etc/dnsmasq.d/99-allowlist.conf

    {
        echo "# Generated by generate-dnsmasq.sh — do not edit manually"
        echo "# Mode: $mode"
        echo "# $(date)"
        echo ""
        echo "no-resolv"
        echo "bind-interfaces"
        echo "listen-address=127.0.0.1"
        echo "port=53"
        echo "domain-needed"
        echo "bogus-priv"
        echo ""

        if [ "$mode" = "locked" ]; then
            if ! ls "$ALLOWLIST_DIR"/allowlist.*.txt &>/dev/null; then
                echo "Error: no allowlist files found in $ALLOWLIST_DIR" >&2
                exit 1
            fi

            while IFS= read -r domain || [ -n "$domain" ]; do
                domain="$(echo "$domain" | xargs)"
                [ -z "$domain" ] && continue
                [[ "$domain" == \#* ]] && continue
                domain="${domain%%#*}"
                domain="$(echo "$domain" | xargs)"
                [ -z "$domain" ] && continue
                domain="${domain#\*.}"
                echo "server=/$domain/$UPSTREAM_V4"
                echo "server=/$domain/$UPSTREAM_V6"
            done < <(cat "$ALLOWLIST_DIR"/allowlist.*.txt | sort -u)

            # Apply deny list overrides (NXDOMAIN for blocked domains)
            if [ -f "$ALLOWLIST_DIR/deny.txt" ]; then
                while IFS= read -r domain || [ -n "$domain" ]; do
                    domain="$(echo "$domain" | xargs)"
                    [ -z "$domain" ] && continue
                    [[ "$domain" == \#* ]] && continue
                    domain="${domain%%#*}"
                    domain="$(echo "$domain" | xargs)"
                    [ -z "$domain" ] && continue
                    echo "address=/$domain/0.0.0.0"
                    echo "address=/$domain/::"
                done < "$ALLOWLIST_DIR/deny.txt"
            fi
        else
            echo "# Forward all queries"
            echo "server=$UPSTREAM_V4"
            echo "server=$UPSTREAM_V6"
        fi
    } > "$DNSMASQ_CONF"

    chown root:root "$DNSMASQ_CONF"
    chmod 644 "$DNSMASQ_CONF"
}

write_config "$MODE"
systemctl restart dnsmasq
echo "dnsmasq: $MODE — deployed to $DNSMASQ_CONF and restarted"
